### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by Blackhawk-TA** [Danielus111/dbotfinal#1]
Hello,

I have noticed that you have re-uploaded my code (https://github.com/Blackhawk-TA/dynoBot).
Unfortunately, you have removed the original license and copyright notice. This is prohibited, regarding the MIT license of my code (https://github.com/Blackhawk-TA/dynoBot/blob/master/LICENSE.md).

The MIT license states that you can modify, distribute and use the software as long as you keep the license and copyright notice.

Therefore you have two options:
1. Delete this repository
2. Delete this repository and fork the original project without deleting the license

Please keep in mind that open source does not mean the software has no owner or copyright.

**Comment by Danielus111** [comment]
Ok i will delete the repository
